name: http_worker
description: HTTP worker is a Dart package that provides a simple interface to process HTTP requests. This package is used by the Unwired package.
version: 1.3.5
homepage: https://github.com/Ayush-Suman/http_worker

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  parser_interface: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
